// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vmmpgwisdmsilvvmfvcs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZtbXBnd2lzZG1zaWx2dm1mdmNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk4MzAyNzAsImV4cCI6MjA3NTQwNjI3MH0.EWgJ9-AoNxd__11BNdUppusvWHkbUK4kyV0s5ean5Xo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});